# if: tag IS present
language: node_js
node_js:
- "10"
sudo: required
services:
- docker
install: false
script: false
deploy:
- provider: script
  script: bash .travis/docker-release.sh
  skip_cleanup: true
  on:
    repo: travisghansen/oauth-external-auth-server
    branch: "master"
- provider: script
  script: bash .travis/docker-release.sh
  skip_cleanup: true
  on:
    repo: travisghansen/oauth-external-auth-server
    tags: true
