# if: tag IS present
# something
language: node_js
node_js:
- "10"
sudo: required
services:
- docker
install: true
script: true
deploy:
- provider: script
  script: bash .travis/docker-release.sh
  skip_cleanup: true
  on:
    repo: travisghansen/external-auth-server
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|next$
- provider: script
  script: bash .travis/docker-release.sh
  skip_cleanup: true
  on:
    repo: travisghansen/external-auth-server
    tags: true
