apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "external-auth-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "external-auth-server.name" . }}
    helm.sh/chart: {{ include "external-auth-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  node-extra-ca-certs: {{ default "" .Values.nodeExtraCaCerts | quote }}
