apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-auth-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "external-auth-server.name" . }}
    helm.sh/chart: {{ include "external-auth-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "external-auth-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "external-auth-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.metrics.port | quote }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: EAS_PORT
              value: "8080"
            {{- if .Values.logLevel }}
            - name: EAS_LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            {{- end }}
            {{- if .Values.storeOpts }}
            - name: EAS_STORE_OPTS
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: store-opts
            {{- end }}
            {{- if .Values.configTokenStores }}
            - name: EAS_CONFIG_TOKEN_STORES
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: config-token-stores
            {{- end }}
            {{- if .Values.configTokens }}
            - name: EAS_CONFIG_TOKENS
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: config-tokens
            {{- end }}
            - name: EAS_CONFIG_TOKEN_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: config-token-sign-secret
            - name: EAS_CONFIG_TOKEN_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: config-token-encrypt-secret
            - name: EAS_ISSUER_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: issuer-sign-secret
            - name: EAS_ISSUER_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: issuer-encrypt-secret
            - name: EAS_COOKIE_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: cookie-sign-secret
            - name: EAS_COOKIE_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: cookie-encrypt-secret
            - name: EAS_SESSION_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: session-encrypt-secret
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

