apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oeas.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oeas.name" . }}
    helm.sh/chart: {{ include "oeas.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oeas.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oeas.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OEAS_PORT
              value: "8080"
            {{- if .Values.storeOpts }}
            - name: OEAS_STORE_OPTS
              valueFrom:
                secretKeyRef:
                  name: {{ include "oeas.fullname" . }}
                  key: store-opts
            {{- end }}
            - name: OEAS_JWT_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "oeas.fullname" . }}
                  key: jwt-sign-secret
            - name: OEAS_PROXY_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "oeas.fullname" . }}
                  key: proxy-encrypt-secret
            - name: OEAS_ISSUER_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "oeas.fullname" . }}
                  key: issuer-encrypt-secret
            - name: OEAS_SESSION_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "oeas.fullname" . }}
                  key: session-encrypt-secret
            - name: OEAS_COOKIE_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "oeas.fullname" . }}
                  key: cookie-sign-secret
            - name: OEAS_COOKIE_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "oeas.fullname" . }}
                  key: cookie-encrypt-secret
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

