apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-auth-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "external-auth-server.name" . }}
    helm.sh/chart: {{ include "external-auth-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "external-auth-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "external-auth-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: EAS_PORT
              value: "8080"
            {{- if .Values.storeOpts }}
            - name: EAS_STORE_OPTS
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: store-opts
            {{- end }}
            - name: EAS_CONFIG_TOKEN_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: config-token-sign-secret
            - name: EAS_PROXY_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: proxy-encrypt-secret
            - name: EAS_ISSUER_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: issuer-encrypt-secret
            - name: EAS_ISSUER_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: issuer-sign-secret
            - name: EAS_SESSION_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: session-encrypt-secret
            - name: EAS_COOKIE_SIGN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: cookie-sign-secret
            - name: EAS_COOKIE_ENCRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "external-auth-server.fullname" . }}
                  key: cookie-encrypt-secret
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

