apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oeas.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "oeas.name" . }}
    helm.sh/chart: {{ include "oeas.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  jwt-sign-secret: {{ required "jwtSignSecret is required" .Values.jwtSignSecret | b64enc | quote }}
  proxy-encrypt-secret: {{ required "proxyEncryptSecret is required" .Values.proxyEncryptSecret | b64enc | quote }}
  issuer-encrypt-secret: {{ required "issuerEncryptSecret is required" .Values.issuerEncryptSecret | b64enc | quote }}
  session-encrypt-secret: {{ required "sessionEncryptSecret is required" .Values.sessionEncryptSecret | b64enc | quote }}
  cookie-sign-secret: {{ required "cookieSignSecret is required" .Values.cookieSignSecret | b64enc | quote }}
  cookie-encrypt-secret: {{ required "cookieEncryptSecret is required" .Values.cookieEncryptSecret | b64enc | quote }}
  {{- if .Values.storeOpts }}
  store-opts: {{ .Values.storeOpts | toJson | b64enc | quote }}
  {{- end }}

