apiVersion: kustomize.drivenow.com.au/v1
kind: ExternalAuthServiceEnvoyFilter
metadata:
  name: frontend-auth
spec:
  # must match the secets used in the eas config
  configTokenSignSecret: 1ba3a359093ea4f7a7b65bb1
  configTokenEncryptSecret: 0f5d0319bb947978a8ea5f79

  # specifies the workload selector and port for targeting the sidecar to filter
  # to target the istio gateway some changes will be needed to change the filter `listenerType: SIDECAR_INBOUND`
  sidecar:
    selector: 
      app: webapp
    port: 80

  # the token is the same shape as eas expectes apart from the htpasswd plugin as it uses a pre-processor to generate the htpasswd on the fly
  token:
    eas:
      plugins:
        - type: htpasswd
          realm: Example

          # can either specify usernames and passwords and the generator will create the htpasswd field
          users: 
            - username: user1x
              password: pass1
            - username: user2
              password: pass2

          # specify the htpasswd directly
          # htpasswd: test:$2y$05$kd/ML6y5v3.VvMpYJQnxLeLC/1qwpLgLa7g0wZ.BpiyNIzCpm3K12